# Generated by Django 2.2.9 on 2020-01-10 08:53

from django.db import migrations, models
import nsupdate.main.models


def gen_http_user(apps, schema_editor):
    Host = apps.get_model('main', 'Host')
    http_user_set = set()
    all_hosts = [row for row in Host.objects.all() ]
    for row in all_hosts:
        http_user = nsupdate.main.models._http_user_generator()
        while http_user in http_user_set:
            http_user = nsupdate.main.models._http_user_generator()
        http_user_set.add(http_user)
        row.http_user = http_user
    for row in all_hosts:
        row.save(update_fields=['http_user'])

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20191230_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='http_user',
            field=models.CharField(max_length=30, unique=True, verbose_name='http user', null=True, default=None),
        ),
        migrations.RunPython(gen_http_user, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='host',
            name='http_user',
            field=models.CharField(max_length=30, unique=True, verbose_name='http user', null=False, default=nsupdate.main.models._http_user_generator),
        ),
    ]
