# Generated by Junie to replace deprecated unique_together and index_together
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0013_alter_host_update_secret"),
    ]

    operations = [
        # Remove deprecated Meta options
        migrations.AlterUniqueTogether(
            name="host",
            unique_together=set(),
        ),
        migrations.AlterIndexTogether(
            name="host",
            index_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="relatedhost",
            unique_together=set(),
        ),
        # Add explicit constraints
        migrations.AddConstraint(
            model_name="host",
            constraint=models.UniqueConstraint(
                fields=("name", "domain"), name="unique_host_domain"
            ),
        ),
        migrations.AddConstraint(
            model_name="relatedhost",
            constraint=models.UniqueConstraint(
                fields=("name", "main_host"), name="unique_relatedhost_name_mainhost"
            ),
        ),
    ]
