# Generated by Django 4.2.29 on 2026-04-05 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_host_update_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedhost',
            name='name_re',
            field=models.CharField(help_text='Blacklisted domain. Evaluated as a regex (search).', max_length=255, unique=True, verbose_name='name regex'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Some arbitrary comment about your domain. If your domain is public, the comment will also be publicly shown.', max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='host',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Some arbitrary comment about your host, e.g. who / what / where this host is', max_length=255, null=True, verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='relatedhost',
            name='comment',
            field=models.CharField(blank=True, default='', help_text='Some arbitrary comment about your host, e.g. who / what / where this host is', max_length=255, null=True, verbose_name='comment'),
        ),
    ]
