# Generated by Django 4.2 on 2023-04-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_host_update_secret'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='host',
            new_name='main_host_name_6d33bf_idx',
            old_fields=('name', 'domain'),
        ),
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='unique_host_domain'),
        ),
    ]
