# Generated by Django 4.2.29 on 2026-03-29 18:12

import django.core.validators
from django.db import migrations, models
import nsupdate.main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blacklistedhost_name_re_alter_domain_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='nameserver2_port',
            field=nsupdate.main.models.RangeIntegerField(default=53, help_text='Port to use', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='nameserver port to use (secondary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver2_protocol',
            field=models.CharField(choices=[('udp', 'udp'), ('tcp', 'tcp'), ('dot', 'DoT (dns-over-tls)'), ('doh', 'DoH (dns-over-https)'), ('doq', 'DoQ (dns-over-quic)')], default='tcp', help_text='Protocol to use', max_length=4, verbose_name='nameserver protocol (secondary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver_port',
            field=nsupdate.main.models.RangeIntegerField(default=53, help_text='Port to use', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='nameserver port to use (primary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver_protocol',
            field=models.CharField(choices=[('udp', 'udp'), ('tcp', 'tcp'), ('dot', 'DoT (dns-over-tls)'), ('doh', 'DoH (dns-over-https)'), ('doq', 'DoQ (dns-over-quic)')], default='tcp', help_text='Protocol to use', max_length=4, verbose_name='nameserver protocol (primary)'),
        ),
        migrations.AddField(
            model_name='domain',
            name='nameserver_update_key_name',
            field=models.CharField(default='', help_text='Name of the key as it exists in bind.conf . Must be the same as it is in the bind configuration.', max_length=128, verbose_name='nameserver update key name'),
        ),
    ]
