# Generated by Django 4.2.29 on 2026-04-06 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_blacklistedhost_name_re_alter_domain_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='host',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='relatedhost',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='host',
            constraint=models.UniqueConstraint(fields=('name', 'domain'), name='unique_host_domain'),
        ),
        migrations.AddConstraint(
            model_name='relatedhost',
            constraint=models.UniqueConstraint(fields=('name', 'main_host'), name='unique_relatedhost_name_mainhost'),
        ),
    ]
