# Generated by Django 5.2.13 on 2026-04-28 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_domain_nameserver2_port_domain_nameserver2_protocol_and_more'),
        ('main', '0016_alter_domain_comment_alter_host_api_auth_result_msg_and_more'),
    ]

    operations = [
    ]
