# Generated by Django 5.2.13 on 2026-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_merge_20260428_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='nameserver_update_key_name',
            field=models.CharField(default='', help_text='Name of the key as it is in your name server configuration, also key names are part of the signature.', max_length=128, verbose_name='nameserver update key name'),
        ),
    ]
