# Generated by Django 2.2.9 on 2019-12-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20141125_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('el', 'Greek'), ('fr', 'French'), ('it', 'Italian')], default='', max_length=10, null=True, verbose_name='language'),
        ),
    ]
