# Generated by Django 5.2.13 on 2026-05-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191230_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('de', 'German'), ('el', 'Greek'), ('fr', 'French'), ('it', 'Italian'), ('hu', 'Hungarian')], default='', max_length=10, null=True, verbose_name='language'),
        ),
    ]
