# badge: https://github.com/nsupdate-info/nsupdate.info/workflows/CI/badge.svg?branch=master

name: CI

on:
  push:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.yml'
    - '**.cfg'
    - '**.ini'
    - 'requirements.d/*'
    - '!docs/**'
  pull_request:
    branches: [ master ]
    paths:
    - '**.py'
    - '**.yml'
    - '**.cfg'
    - '**.ini'
    - 'requirements.d/*'
    - '!docs/**'

jobs:
  lint:

    runs-on: ubuntu-22.04
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 src scripts conftest.py

  tox:

    needs: lint
    strategy:
      fail-fast: true
      matrix:
        include:
            - os: ubuntu-22.04
              python-version: '3.8'
              toxenv: py38
            - os: ubuntu-22.04
              python-version: '3.9'
              toxenv: py39
            - os: ubuntu-22.04
              python-version: '3.10'
              toxenv: py310

    env:
      TOXENV: ${{ matrix.toxenv }}

    runs-on: ${{ matrix.os }}
    timeout-minutes: 40

    steps:
    - uses: actions/checkout@v3
      with:
        # just fetching 1 commit is not enough for setuptools-scm, so we fetch all
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.d/dev.txt') }}
        restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

    - name: Install and configure bind
      run: |
        bash scripts/ci/install-bind.sh
    - name: Install Python tools and tox
      run: |
        python -m pip install --upgrade pip setuptools wheel tox
    - name: run tox env
      run: |
        tox --skip-missing-interpreters
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      env:
        OS: ${{ runner.os }}
        python: ${{ matrix.python-version }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        env_vars: OS, python
